### ISSUE TITLE
The dataset University-Release is missing images？

### ISSUE THREAD

**Issue by wpumain** [layumi/University1652-Baseline#36]
Thank you for providing the University1652 dataset.
There is no image In the class 1057, 1100, 1116, 1237, 1326, 1350, 1351, 1355, 1356, 1357, 1358, 1453 under the "/train/google" folder 。Is this because I have a problem downloading?

**Comment by layumi** [comment]
Hi @wpumain 

They are correct.  You should leave them as empty, otherwise the class name is not aligned with satellite and drone. 

Since we use two strong filters, No ``indoor'' & No ``ambiguous'' images belonging to two buildings. 
We remove many inreliable samples.  So some online collected ``google'' folders are empty.

**Comment by wpumain** [comment]
Think you for your help!
